### PR TITLE
fix(FilePreview): Fix file preview

### LINKED ISSUE #690: Files - Crash when trying to preview file
**Issue:** 
If you upload a file in the Files Panel and try to preview it, it will open the file browser and once you close that the app will crash 

(At the bottom I will show my trace and if you send me a DM I can send you the profile as well)

**OS**
All

**STR:**
1. Upload a file 
2. Preview the file 
3. Close file browser that opens up
4. App crashes 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/233245532-fcd00629-7749-4ea0-9458-6bd8fd84460f.mov

**trace2:**

2023-04-19 22:43:43 | DEBUG | starting uplink
2023-04-19 22:43:43 | TRACE | rendering bootstrap
2023-04-19 22:43:43 | TRACE | initializing tesseract
2023-04-19 22:43:43 | TRACE | rendering auth wrapper
2023-04-19 22:43:43 | DEBUG | warp initialization
2023-04-19 22:43:43 | TRACE | rendering unlock layout
2023-04-19 22:43:43 | TRACE | Initializing Multipass
2023-04-19 22:43:43 | DEBUG | add_to_themes: /Users/phillwisniewski/.uplink/themes
2023-04-19 22:43:43 | DEBUG | add_to_themes: ui/extra/themes
2023-04-19 22:43:43 | DEBUG | Identity doesnt exist. Waiting for it to load or to be created
2023-04-19 22:43:43 | TRACE | Initializing Raygun Extension
2023-04-19 22:43:43 | TRACE | Identity doesnt exist. Waiting for it to load or to be created
2023-04-19 22:43:43 | DEBUG | received warp cmd: Tesseract { AccountExists } 
2023-04-19 22:43:43 | DEBUG | account_exists: true
2023-04-19 22:43:43 | TRACE | rendering unlock layout
2023-04-19 22:43:46 | TRACE | rendering unlock layout
2023-04-19 22:43:46 | TRACE | rendering unlock layout
2023-04-19 22:43:46 | TRACE | rendering unlock layout
2023-04-19 22:43:46 | TRACE | rendering unlock layout
2023-04-19 22:43:46 | DEBUG | received warp cmd: MultiPass { TryLogIn } 
2023-04-19 22:43:46 | INFO | Fetching keypair from tesseract
2023-04-19 22:43:46 | INFO | Have keypair with peer id: 12D3KooWBiZ85378PC5Px3EfgrVyCHgMxwStRVEJpRTBvP6AZ3hJ
2023-04-19 22:43:46 | INFO | Instance will be persistent
2023-04-19 22:43:46 | INFO | Path set: /Users/phillwisniewski/.uplink/.user/warp
2023-04-19 22:43:46 | INFO | Starting ipfs
2023-04-19 22:43:46 | INFO | Relay client enabled. Loading relays
2023-04-19 22:43:46 | INFO | Identity loaded with did:key:z6MkgMSzv9mrXqJNeeZwjpiUGb9XJBg6ogQBYr16NfuHaKkk
2023-04-19 22:43:46 | INFO | Identity store initialized
2023-04-19 22:43:46 | INFO | friends store initialized
2023-04-19 22:43:46 | INFO | multipass initialized
2023-04-19 22:43:46 | DEBUG | warp_runner::manager::run
2023-04-19 22:43:46 | TRACE | rendering app_bootstrap
2023-04-19 22:43:46 | DEBUG | add_to_themes: /Users/phillwisniewski/.uplink/themes
2023-04-19 22:43:46 | DEBUG | add_to_themes: ui/extra/themes
2023-04-19 22:43:46 | TRACE | rendering app
2023-04-19 22:43:46 | TRACE | rendering get_update_icon
2023-04-19 22:43:46 | DEBUG | Loaded 0 extensions.
2023-04-19 22:43:46 | DEBUG | WARP CMD: MultiPass { InitializeFriends } 
2023-04-19 22:43:46 | INFO | list_incoming_request;
2023-04-19 22:43:46 | TRACE | rendering app
2023-04-19 22:43:46 | TRACE | -- list_incoming_request;
2023-04-19 22:43:46 | TRACE | init friends with 0 total
2023-04-19 22:43:46 | INFO | list_outgoing_request;
2023-04-19 22:43:46 | TRACE | -- list_outgoing_request;
2023-04-19 22:43:46 | INFO | block_list;
2023-04-19 22:43:46 | TRACE | -- block_list;
2023-04-19 22:43:46 | DEBUG | WARP CMD: Constellation { GetItemsFromCurrentDirectory } 
2023-04-19 22:43:46 | DEBUG | Updating directories opened to browse
2023-04-19 22:43:46 | INFO | Get items from current directory worked!
2023-04-19 22:43:46 | DEBUG | WARP CMD: RayGun { InitializeConversations } 
2023-04-19 22:43:46 | ERROR | failed to initialize conversations: RayGun extension is unavailable
2023-04-19 22:43:46 | TRACE | init friends
2023-04-19 22:43:46 | TRACE | init items
2023-04-19 22:43:46 | ERROR | command canceled: oneshot canceled
2023-04-19 22:43:46 | TRACE | rendering app
2023-04-19 22:43:46 | DEBUG | Initializing or fetch ipfs
2023-04-19 22:43:46 | TRACE | Identity found. Initializing store
2023-04-19 22:43:46 | TRACE | Initializing internal store
2023-04-19 22:43:46 | INFO | Initializing MessageStore
2023-04-19 22:43:46 | INFO | Loading existing conversations task
2023-04-19 22:43:46 | INFO | MessagingStore task created
2023-04-19 22:43:46 | INFO | Loading queue
2023-04-19 22:43:46 | TRACE | rendering get_update_icon
2023-04-19 22:43:46 | TRACE | rendering app
2023-04-19 22:43:46 | TRACE | rendering get_update_icon
2023-04-19 22:43:46 | TRACE | rendering app
2023-04-19 22:43:46 | TRACE | rendering app
2023-04-19 22:43:46 | TRACE | rendering get_update_icon
2023-04-19 22:43:47 | ERROR | failed to check for release: error decoding response body: missing field `tag_name` at line 4 column 1
2023-04-19 22:43:47 | DEBUG | WARP CMD: RayGun { InitializeConversations } 
2023-04-19 22:43:47 | TRACE | init convs with 0 total
2023-04-19 22:43:47 | TRACE | init chats
2023-04-19 22:43:47 | TRACE | rendering app
2023-04-19 22:43:47 | TRACE | rendering app
2023-04-19 22:43:47 | TRACE | rendering get_update_icon
2023-04-19 22:43:47 | TRACE | starting warp_runner use_future
2023-04-19 22:43:47 | TRACE | rendering chats sidebar layout
2023-04-19 22:43:50 | TRACE | rendering topbar
2023-04-19 22:43:50 | TRACE | rendering chats sidebar layout
2023-04-19 22:43:51 | DEBUG | WARP CMD: Constellation { GetItemsFromCurrentDirectory } 
2023-04-19 22:43:51 | TRACE | rendering topbar
2023-04-19 22:43:51 | INFO | Get items from current directory worked!
2023-04-19 22:43:51 | TRACE | rendering topbar
2023-04-19 22:43:51 | TRACE | rendering app
2023-04-19 22:43:51 | TRACE | rendering get_update_icon
2023-04-19 22:43:51 | TRACE | rendering topbar
2023-04-19 22:43:51 | TRACE | rendering chats sidebar layout
2023-04-19 22:43:53.066 uplink[57579:2657666] +[CATransaction synchronize] called within transaction
2023-04-19 22:43:59 | DEBUG | WARP CMD: Constellation { UploadFiles { files_path: ["/Users/phillwisniewski/Library/Mobile Documents/com~apple~CloudDocs/QA Tools/Sample Profile Pics/pic6.jpg"] }  } 
2023-04-19 22:43:59 | INFO | Duplicate name, changing file name to pic6 (1).jpg
2023-04-19 22:43:59 | TRACE | rendering topbar
2023-04-19 22:43:59 | INFO | Starting upload for pic6 (1).jpg
2023-04-19 22:43:59 | INFO | 0% completed -> written 0 bytes
2023-04-19 22:43:59 | INFO | 11% completed -> written 4.10 kB
2023-04-19 22:43:59 | INFO | 22% completed -> written 8.19 kB
2023-04-19 22:43:59 | INFO | 33% completed -> written 12.29 kB
2023-04-19 22:43:59 | INFO | 44% completed -> written 16.38 kB
2023-04-19 22:43:59 | INFO | 55% completed -> written 20.48 kB
2023-04-19 22:43:59 | INFO | 67% completed -> written 24.58 kB
2023-04-19 22:43:59 | INFO | 78% completed -> written 28.67 kB
2023-04-19 22:43:59 | INFO | 89% completed -> written 32.77 kB
2023-04-19 22:43:59 | INFO | 100% completed -> written 36.66 kB
2023-04-19 22:43:59 | INFO | pic6 (1).jpg has been uploaded with 36.66 kB
2023-04-19 22:43:59 | INFO | Image Thumbnail uploaded
2023-04-19 22:43:59 | INFO | "pic6 (1).jpg" file uploaded!
2023-04-19 22:43:59 | INFO | Get items from current directory worked!
2023-04-19 22:44:00 | TRACE | rendering topbar
2023-04-19 22:44:00 | TRACE | rendering app
2023-04-19 22:44:00 | TRACE | rendering get_update_icon
2023-04-19 22:44:00 | TRACE | rendering topbar
2023-04-19 22:44:00 | TRACE | rendering chats sidebar layout
2023-04-19 22:44:02 | DEBUG | state::mutate: AddFilePreview
2023-04-19 22:44:02 | TRACE | rendering app
2023-04-19 22:44:02 | TRACE | rendering get_update_icon
2023-04-19 22:44:02 | TRACE | rendering topbar
2023-04-19 22:44:02 | TRACE | rendering chats sidebar layout
panic occurred: "Cannot catch errors during rebuild" at file /Users/phillwisniewski/.cargo/git/checkouts/dioxus-1e619ce595d3799d/d521da1/packages/core/src/virtual_dom.rs, line 548
2023-04-19 22:43:43 | DEBUG | starting uplink
2023-04-19 22:43:43 | DEBUG | warp initialization
2023-04-19 22:43:43 | DEBUG | add_to_themes: /Users/phillwisniewski/.uplink/themes
2023-04-19 22:43:43 | DEBUG | add_to_themes: ui/extra/themes
2023-04-19 22:43:43 | DEBUG | received warp cmd: Tesseract { AccountExists } 
2023-04-19 22:43:43 | DEBUG | account_exists: true
2023-04-19 22:43:46 | DEBUG | received warp cmd: MultiPass { TryLogIn } 
2023-04-19 22:43:46 | DEBUG | warp_runner::manager::run
2023-04-19 22:43:46 | DEBUG | add_to_themes: /Users/phillwisniewski/.uplink/themes
2023-04-19 22:43:46 | DEBUG | add_to_themes: ui/extra/themes
2023-04-19 22:43:46 | DEBUG | Loaded 0 extensions.
2023-04-19 22:43:46 | DEBUG | WARP CMD: MultiPass { InitializeFriends } 
2023-04-19 22:43:46 | DEBUG | WARP CMD: Constellation { GetItemsFromCurrentDirectory } 
2023-04-19 22:43:46 | DEBUG | Updating directories opened to browse
2023-04-19 22:43:46 | INFO | Get items from current directory worked!
2023-04-19 22:43:46 | DEBUG | WARP CMD: RayGun { InitializeConversations } 
2023-04-19 22:43:46 | ERROR | failed to initialize conversations: RayGun extension is unavailable
2023-04-19 22:43:46 | ERROR | command canceled: oneshot canceled
2023-04-19 22:43:47 | ERROR | failed to check for release: error decoding response body: missing field `tag_name` at line 4 column 1
2023-04-19 22:43:47 | DEBUG | WARP CMD: RayGun { InitializeConversations } 
2023-04-19 22:43:51 | DEBUG | WARP CMD: Constellation { GetItemsFromCurrentDirectory } 
2023-04-19 22:43:51 | INFO | Get items from current directory worked!
2023-04-19 22:43:59 | DEBUG | WARP CMD: Constellation { UploadFiles { files_path: ["/Users/phillwisniewski/Library/Mobile Documents/com~apple~CloudDocs/QA Tools/Sample Profile Pics/pic6.jpg"] }  } 
2023-04-19 22:43:59 | INFO | Duplicate name, changing file name to pic6 (1).jpg
2023-04-19 22:43:59 | INFO | Starting upload for pic6 (1).jpg
2023-04-19 22:43:59 | INFO | 0% completed -> written 0 bytes
2023-04-19 22:43:59 | INFO | 11% completed -> written 4.10 kB
2023-04-19 22:43:59 | INFO | 22% completed -> written 8.19 kB
2023-04-19 22:43:59 | INFO | 33% completed -> written 12.29 kB
2023-04-19 22:43:59 | INFO | 44% completed -> written 16.38 kB
2023-04-19 22:43:59 | INFO | 55% completed -> written 20.48 kB
2023-04-19 22:43:59 | INFO | 67% completed -> written 24.58 kB
2023-04-19 22:43:59 | INFO | 78% completed -> written 28.67 kB
2023-04-19 22:43:59 | INFO | 89% completed -> written 32.77 kB
2023-04-19 22:43:59 | INFO | 100% completed -> written 36.66 kB
2023-04-19 22:43:59 | INFO | pic6 (1).jpg has been uploaded with 36.66 kB
2023-04-19 22:43:59 | INFO | Image Thumbnail uploaded
2023-04-19 22:43:59 | INFO | "pic6 (1).jpg" file uploaded!
2023-04-19 22:43:59 | INFO | Get items from current directory worked!
2023-04-19 22:44:02 | DEBUG | state::mutate: AddFilePreview

2023-04-19 22:44:02.225 uplink[57579:2657666] +[CATransaction synchronize] called within transaction
2023-04-19 22:44:03 | DEBUG | terminating warp_runner thread

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Fix file preview 
image

- 

### Which issue(s) this PR fixes 🔨

- Resolve #690

### CODE REVIEW

**Review by phillsatellite — APPROVED** [review]

File: ui/src/layouts/file_preview.rs [hunk 1]
```diff
@@ -210,9 +190,9 @@ fn resize_window(
     Some(())
 }
 
-fn update_theme_colors(state: UseSharedState<State>) -> String {
+fn update_theme_colors() -> String {
+    let state = State::load();
```
Comment (dariusc93) [inline ui/src/layouts/file_preview.rs:194]: Down the road it may be best to avoid loading directly from the state since there could be many things that could trigger a chance and possibly cause a race in some way with how data is handled in memory vs how its stored then loaded from disk.

**Review by dariusc93 — APPROVED** [review]
