### PR TITLE
fix(textarea): placeholder alignment jitter

### LINKED ISSUE #973: bug(responsive): issue with textbox
**Issue:**
When in mobile view, the _say something_ doesn't fit the textbox 

**OS:**
All

**Screenshot:**
mobile:chat:textbox

### PR DESCRIPTION
**Pull request by Jekrimo**
### What this PR does 📖

- height is locked for input until user types

### Which issue(s) this PR fixes 🔨

- Resolve #973

### CODE REVIEW

**Comment by phillsatellite** [comment]
I noticed when testing that if you switch to chat "say something" will still be sitting a little high but if you wait a couple seconds without clicking anything it will self adjust itself. So it does technically work it just takes a few moments I tested this with debug and release with the same behavior. If its possible to have it update a little faster I think thatd be awesome but if its super complex and would wanna work on it further in a separate ticket I could totally understand 

https://github.com/Satellite-im/Uplink/assets/93608357/325e2099-d5db-4cd8-9d20-7064e7bcc8f9

**Comment by Jekrimo** [comment]
Great catch, I hadn't seen it related to the sidebar in this way, I'm on it!

File: kit/src/elements/textarea/script.js [hunk 1]
```diff
@@ -51,6 +51,11 @@ function updateHeight(element) {
     element.style.height = element.scrollHeight + "px";
 }
 
+function appResizeListener(e) {
```
Comment (lgmarchi) [inline kit/src/elements/textarea/script.js]: It should not be better in `update_input_height.js` file? 

And this script runs before element render, so maybe listener can work faster.

Comment (Jekrimo) [reply kit/src/elements/textarea/script.js]: honestly didn't even see update_input_height.js but that file contains  NEARLY the same code at the script.js so that's confusing

**Comment by stavares843** [comment]
missing linter 🔨

**Comment by stavares843** [comment]
https://github.com/Satellite-im/Uplink/actions/runs/5681831674/job/15398829422?pr=1003

**Comment by Jekrimo** [comment]
> https://github.com/Satellite-im/Uplink/actions/runs/5681831674/job/15398829422?pr=1003

forgot to run it, thank you!

**Comment by stavares843** [comment]
thanks for checking! 🔨 is returning error about the following

https://github.com/Satellite-im/Uplink/actions/runs/5683737366/job/15404919221?pr=1003

**Comment by phillsatellite** [comment]
So on MacOS only if you minimize all the way it will just appear as "say" but I discussed with Sara and we think its still able to be approved just wanted to mention the findings 💥 

https://github.com/Satellite-im/Uplink/assets/93608357/b8b4dd4f-8e26-4fa2-acb3-554770a6dbdc

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
yes i agree with Phil, should appear or a ''...'' or make the copy smaller or the font smaller instead of just ''say''

**Comment by Jekrimo** [comment]
Weird! I agree, maybe make a separate ticket, especially since it's one os specific.

File: kit/src/elements/textarea/script.js [hunk 2]
```diff
@@ -39,6 +12,13 @@ for (let i = 0; i < textareas.length; i++) {
     }
 }
 
+textareas[0].addEventListener("keypress", (event) => {
```
Comment (lgmarchi) [inline kit/src/elements/textarea/script.js:15]: Jeff, this code is good. Just a question, don't we have height problem when we send message using send button and mouse?

File: ui/src/components/chat/sidebar.rs [hunk 3]
```diff
@@ -506,7 +507,10 @@ pub fn Sidebar(cx: Scope<Props>) -> Element {
                                 with_badge: badge,
                                 onpress: move |_| {
                                     state.write().mutate(Action::ChatWith(&chat_with.id, false));
-                                    if state.read().ui.is_minimal_view() {
+                                    let desktop = use_window(cx);
```
Comment (lgmarchi) [inline ui/src/components/chat/sidebar.rs]: My friend, it is better to avoid declare this hook inside onpress, and declare it before cx.render.

**Review by lgmarchi — APPROVED** [review]
LGTM, just let a question and a small suggestion.

File: ui/src/components/chat/sidebar.rs (hunk 3 above)
Comment (Jekrimo) [reply ui/src/components/chat/sidebar.rs]: Super good call!, that fixed my crash! I was so confused, fixed, and thanks for looking out!

File: kit/src/elements/textarea/script.js (hunk 2 above)
Comment (Jekrimo) [reply kit/src/elements/textarea/script.js:15]: I haven't seen that one, I'll do some testing around it and check

**Review by dariusc93 — APPROVED** [review]
