### PR TITLE
fix(chat): Chat whitespace fix

### LINKED ISSUE #888: bug(chat): Any spaces on new lines will not appear when sent
**Issue:**
When you start a new line of text, if you put any spaces in the start of the line they will now show up in chat 

**OS:**
All

**Screenshot**
image

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fixes leading whitespace ignored

### Which issue(s) this PR fixes 🔨

- Resolve #888

### CODE REVIEW

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
Captura de ecrã 2023-06-14, às 01 10 36

missing linter 🔨

**Review by stavares843 — APPROVED** [review]

File: kit/src/components/message/mod.rs [hunk 1]
```diff
@@ -146,7 +146,8 @@ pub fn Message<'a>(cx: Scope<'a, Props<'a>>) -> Element<'a> {
 
     // if markdown support is enabled, we will create it, otherwise we will just pass text.
     let formatted_text = if cx.props.parse_markdown {
-        let parser = pulldown_cmark::Parser::new(&text);
+        let txt = text.trim().replace(" ", "&nbsp;"); // need to do this else leading whitespaces are ignored
```
Comment (dariusc93) [inline kit/src/components/message/mod.rs]:
```suggestion
        let txt = text.trim().replace(' ', "&nbsp;"); // need to do this else leading whitespaces are ignored
```

**Review by dariusc93 — APPROVED** [review]
