### PR TITLE
fix(chat): Scroll to time ago element

### LINKED ISSUE #1333: bug(chat): User needs to scroll down to see timestamp
**Issue:**
 User has to scroll down to see the timestamp of the message they just sent 
 
 **OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/9933ee0f-49ab-4df7-94c0-e84d2e34e331

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fixes chat to bottom scroll not including the timestamp element

### Which issue(s) this PR fixes 🔨

- Resolve #1333

### CODE REVIEW

File: ui/src/layouts/chats/scripts/scroll_to_bottom.js [hunk 1]
```diff
@@ -1,4 +1,10 @@
 // returns for eval
 var message = document.getElementById("$MESSAGE_ID");
+var time = message.parentElement.parentElement.getElementsByClassName("time-ago")[0];
+// try find the time-ago element
+if (time) {
+    message = time;
+}
+console.log("msg ", message);
```
Comment (stavares843) [inline ui/src/layouts/chats/scripts/scroll_to_bottom.js]: do we need the console log? 🔨

**Review by stavares843 — APPROVED** [review]
fixed 🎉

**Review by phillsatellite — APPROVED** [review]

File: ui/src/layouts/chats/scripts/scroll_to_bottom.js (hunk 1 above)
Comment (Flemmli97) [reply ui/src/layouts/chats/scripts/scroll_to_bottom.js]: removed

**Review by sdwoodbury — APPROVED** [review]
