### PR TITLE
fix(GroupUsers): Let find users with case non sensitive

### LINKED ISSUE #1039: chat(improvement): make search not case sensitive
STR:
- go to group list
- Luis is there
- search by Luis
- works
- search by luis
- no results

Captura de ecrã 2023-07-24, às 20 11 28

Captura de ecrã 2023-07-24, às 20 11 31

Captura de ecrã 2023-07-24, às 20 11 34

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Let find users with case non sensitive
image

### Which issue(s) this PR fixes 🔨

- Resolve #1039

### CODE REVIEW

**Review by dariusc93 — APPROVED** [review]

File: ui/src/components/chat/group_users.rs [hunk 1]
```diff
@@ -102,7 +102,7 @@ fn render_friends(cx: Scope<FriendsProps>) -> Element {
                                 if name.len() < name_prefix.len() {
                                     false
                                 } else {
-                                    &name[..(name_prefix.len())] == name_prefix
+                                    name[..(name_prefix.len())].eq_ignore_ascii_case(&name_prefix)
```
Comment (dariusc93) [inline ui/src/components/chat/group_users.rs]: This should correct the lint warning
```suggestion
                                    name[..(name_prefix.len())].eq_ignore_ascii_case(name_prefix)
```

**Review by stavares843 — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]
