### PR TITLE
fix(mobile): adjust icon and label for input space on mobile

### LINKED ISSUE #1562: username crowded on friends mobile page
image

### PR DESCRIPTION
**Pull request by Jekrimo**
### What this PR does 📖

- 

### Which issue(s) this PR fixes 🔨

- Resolve #1562

### CODE REVIEW

File: ui/src/components/friends/add.rs [hunk 1]
```diff
@@ -102,6 +102,17 @@ pub fn AddFriend(cx: Scope) -> Element {
     let username = identity.username();
     let short_name = format!("{}#{}", username, short_id);
     let short_name_context = short_name.clone();
+    let add_friend_lable = if !state.read().ui.is_minimal_view() {
+        get_local_text("uplink.add")
+    } else {
+        String::from("")
```
Comment (dariusc93) [inline ui/src/components/friends/add.rs]:
```suggestion
        String::new()
```

Comment (Jekrimo) [reply ui/src/components/friends/add.rs]: Never seen this update for incorporating changes, so cool. Great catch, thanks Darius!!

**Review by dariusc93 — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]
