### PR TITLE
fix(Group): Prevent members from removing others

### LINKED ISSUE #1904: bug(groups): Non-creator of group cannot remove other users
**Issue:** There seems to be an issue on dev if you are in a group and you are not the creator regardless of the group settings you will be unable to remove anyone from the group. When you attempt to you get a error in the log that says 

2024-03-06 11:48:11 | ERROR | common/src/warp_runner/manager/commands/raygun_commands.rs:539 | failed to remove did:key:z6MkrvMLehUoUDmnwoYmFepTWwJGioUvKarhqyEXikVKkCRm from group conv: ed72f28c-2b64-4778-9224-f19c745e8cc4. Error: Public key is invalid

**OS:**
MacOS
Windows
Linux

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/b7e54e89-2779-4bb4-8308-d2539dbf398b

### PR DESCRIPTION
**Pull request by lgmarchi**
### Which issue(s) this PR fixes 🔨

- Resolve #1904

### CODE REVIEW

**Review by stavares843 — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

File: ui/src/layouts/chats/presentation/chat/edit_group.rs [hunk 1]
```diff
@@ -44,6 +45,16 @@ pub fn EditGroup(cx: Scope) -> Element {
...
+    let creator_id_vector = Vec::from_iter(
+        state
+            .read()
+            .get_active_chat()
+            .unwrap()
+            .creator
+            .iter()
+            .cloned(),
+    );
+    let creator_id = creator_id_vector.first().cloned()?;
```
Comment (dariusc93) [inline ui/src/layouts/chats/presentation/chat/edit_group.rs]: You can try the creator field (and might as well do the same for `get_active_chat()` unless you wish to panic to treat it as a bug if its `None`?)

```suggestion
    let creator_id = state.read().get_active_chat()?.creator.clone()?;
```

**Review by dariusc93 — COMMENTED** [review]
Left one comment but besides that LGTM

File: ui/src/layouts/chats/presentation/chat/edit_group.rs (hunk 1 above)
Comment (lgmarchi) [reply ui/src/layouts/chats/presentation/chat/edit_group.rs]: Done. Thanks for the tip!

**Review by dariusc93 — APPROVED** [review]
