### PR TITLE
fix(EditMessage): Fix edit message with file sent

### LINKED ISSUE #689: Chat - File message will delete if you edit with no chars
**Issue:**
When you send a file in chat without any context added to the message. If you edit it and then back out of the edit the message will be delete 

**OS:**
Windows 
Mac 
Linux 

**STR:**
1. Upload file in chat but do not add a message to it 
2. Click edit message 
3. Click out of edit message 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/233241863-f1453f55-5b45-4e0d-bb3d-52a35a929517.mov

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Fix edit message when have file attachment with no char 

https://user-images.githubusercontent.com/63157656/233449067-3f6cfd8a-292e-4a6c-8e3a-681fd4916311.mov

- 

### Which issue(s) this PR fixes 🔨

- Resolve #689

### CODE REVIEW

**Review by phillsatellite — APPROVED** [review]

File: ui/src/components/chat/compose/messages.rs [hunk 1]
```diff
@@ -676,8 +676,8 @@ fn render_message<'a>(cx: Scope<'a, MessageProps<'a>>) -> Element<'a> {
                     edit_msg.set(None);
                     let msg = update.split('\n').collect::<Vec<_>>();
                     let is_valid = msg.iter().any(|x| !x.trim().is_empty());
-                    let msg = msg.iter().map(|x| x.to_string()).collect();
-                    if message.inner.value() == msg {
+                    let msg: Vec<String> = msg.iter().map(|x| x.to_string()).collect();
+                    if message.inner.value() == msg || msg.get(0).map(|s| s.to_owned()).unwrap_or("".to_owned()).is_empty() {
```
Comment (dariusc93) [inline ui/src/components/chat/compose/messages.rs]:
```suggestion
                    if message.inner.value() == msg || msg.first().map(|s| s.to_owned()).unwrap_or_default().is_empty() {
```

**Review by dariusc93 — APPROVED** [review]

**Comment by dariusc93** [comment]
the UI automated test (build-app and build-windows) can be ignored here since them failing is unrelated to this PR.

**Review by sdwoodbury — APPROVED** [review]
since it passed QA I'm assuming the behavior is correct. The code looks good.
