### PR TITLE
fix(notification): make sound when chat UI is not active

### LINKED ISSUE #306: Notifications - Notification sound not coming in
**Issue:** If the User has only 1 friend added, and they are exploring through the app (not in that active chat) they won't get any sound when they receive new messages, like the app thinks the user is still in that active chat, even though they are in Settings/Files/etc. If the User is focused outside of the app Notification sound works fine

**OS:**
-Windows
-Mac

**STR:**
1, Add one friend on Uplink 
2. Start a chat with them
3. Now leave the chat, but have the other user continue to message you 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/219460259-a04ffe4e-efef-4a18-97a8-506e6736a506.mov

### PR DESCRIPTION
**Pull request by ealmloff**
### What this PR does 📖

- Remove the active chat when the chat UI is removed which enables notification sounds when in non-chat sections of the app like settings.

### Which issue(s) this PR fixes 🔨

- Resolve #306

### CODE REVIEW

**Review by InfamousVague — APPROVED** [review]

File: ui/src/utils/lifecycle.rs [hunk 1]
```diff
@@ -0,0 +1,18 @@
+use dioxus::prelude::*;
+
+pub fn use_on_unmount<F: FnOnce() + 'static>(cx: &ScopeState, on_unmount: F) -> &LifeCycle<F> {
```
Comment (InfamousVague) [inline ui/src/utils/lifecycle.rs:3]: this is especially useful to know!

**Review by InfamousVague — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]
