### PR TITLE
fix(welcome): make settings welcome active again

### LINKED ISSUE #471: Settings - Welcome message missing
**Issue:** When creating a new account when you go to Settings/Profile there should be a welcome message with the mascot. It looks like it went missing 

**OS:**
-MacOS
-Windows
-Linux

**Screen recording:**

https://user-images.githubusercontent.com/93608357/225948292-101d2b45-cf26-48e0-91ca-57cecd8644d3.mov

### PR DESCRIPTION
**Pull request by Jekrimo**
### What this PR does 📖

- welcome img in settings was relying on a default bool that wasn't working. Added some simple logic to make welcome dismissible 

### Which issue(s) this PR fixes 🔨

- Resolve #471

### CODE REVIEW

**Review by phillsatellite — APPROVED** [review]

File: common/src/state/ui.rs [hunk 1]
```diff
@@ -159,6 +160,9 @@ impl UI {
             desktop_context.close_window(id);
         };
     }
+    pub fn settings_welcome(&mut self) {
```
Comment (lgmarchi) [inline common/src/state/ui.rs:163]: For function, name of this function would be better as an action name, like "show_settings_welcome_screen"

**Review by lgmarchi — APPROVED** [review]
LGTM.

**Review by dariusc93 — APPROVED** [review]
