### PR TITLE
fix(Loader): Fix loader on buttons

### LINKED ISSUE #1706: bug(ui): update loading indicator when removing/blocking a friend
**Issue:**
When you remove a friend and the button goes to grey to indicate loading, the loading indicator and remove friend icon will both show

**OS:**
All

**Screenshot and steps to reproduce:**

- Go to Friends page
- Remove friend
- Notice button 

Screenshot 2024-01-12 at 3 21 01 PM
Screenshot 2024-01-12 at 3 24 39 PM

### PR DESCRIPTION
**Pull request by lgmarchi**
### Which issue(s) this PR fixes 🔨

- Resolve #1706

### CODE REVIEW

File: kit/src/elements/button/mod.rs [hunk 1]
```diff
@@ -79,6 +79,8 @@ pub fn Button<'a>(cx: Scope<'a, Props<'a>>) -> Element<'a> {
         }
     );
 
+    let show_icon = cx.props.loading.unwrap_or(false) || cx.props.icon.is_some();
```
Comment (dariusc93) [inline kit/src/elements/button/mod.rs]: a boolean default will always be false

```suggestion
    let show_icon = cx.props.loading.unwrap_or_default() || cx.props.icon.is_some();
```

File: kit/src/elements/button/mod.rs [hunk 2]
```diff
@@ -135,15 +130,15 @@ pub fn Button<'a>(cx: Scope<'a, Props<'a>>) -> Element<'a> {
...
                     )
                 }
-                if let Some(_icon) = cx.props.icon {
+                if show_icon {
                     rsx!(
                         // for props, copy the defaults passed in by IconButton
                         common::icons::Icon {
                             ..common::icons::IconProps {
-                                class: None,
+                                class: if cx.props.loading.unwrap_or(false) {Some("spin-container-for-button")} else {None},
```
Comment (dariusc93) [inline kit/src/elements/button/mod.rs]:
```suggestion
                                class: if cx.props.loading.unwrap_or_default() {Some("spin-container-for-button")} else {None},
```

File: kit/src/elements/button/mod.rs [hunk 3]
```diff
@@ -135,15 +130,15 @@ pub fn Button<'a>(cx: Scope<'a, Props<'a>>) -> Element<'a> {
...
                                 size: 20,
                                 fill:"currentColor",
-                                icon: _icon,
+                                icon: if cx.props.loading.unwrap_or(false) {Icon::Loader} else {cx.props.icon.unwrap()},
```
Comment (dariusc93) [inline kit/src/elements/button/mod.rs]:
```suggestion
                                icon: if cx.props.loading.unwrap_or_default() {Icon::Loader} else {cx.props.icon.unwrap()},
```

File: kit/src/elements/button/mod.rs (hunk 2 above)
Comment (dariusc93) [reply kit/src/elements/button/mod.rs]: We would instead take advantage of `then` so if `loading` is true, it would provide `Option::Some` otherwise it would be `Option::None`

```suggestion
                                class: if cx.props.loading.unwrap_or_default().then(||"spin-container-for-button"),
```

File: kit/src/elements/button/mod.rs (hunk 3 above)
Comment (dariusc93) [reply kit/src/elements/button/mod.rs]: ditto

**Review by dariusc93 — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]
