### PR TITLE
fix(BugModal): bugchat opening image previews highlights chat list avatars

### LINKED ISSUE #1061: bug(chat): opening image previews highlights chat list avatars
STR:
- go to chat
- add a group chat
- send image
- click on image
- appears like this

Captura de ecrã 2023-08-01, às 21 55 05

macOS, m1

### PR DESCRIPTION
**Pull request by lgmarchi**
### 3. Remove unnecessary code
- 

### Which issue(s) this PR fixes 🔨

- Resolve #1061

### CODE REVIEW

**Review by sdwoodbury — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Comment by phillsatellite** [comment]
Leaving QA Tested off so Sara can get the chance to check it out as well

File: kit/src/layout/modal/mod.rs [hunk 1]
```diff
@@ -14,16 +15,25 @@ pub struct Props<'a> {
...
     cx.render(rsx!(cx.props.open.then(|| rsx!(
-        div {
-            class: "modal",
-            aria_label: "modal",
-            onclick: move |_| cx.props.onclose.call(()),
-            Button {
-                icon: Icon::XMark,
-                appearance: Appearance::Primary,
-                onpress: move |_| cx.props.onclose.call(()),
+        // HACK: Necessay to avoid unwanted context menu
```
Comment (stavares843) [inline kit/src/layout/modal/mod.rs:18]:
```suggestion
        // HACK: Necessary to avoid unwanted context menu
```

**Review by stavares843 — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]
