### PR TITLE
fix(login): change ordering of account creation pages

### LINKED ISSUE #1968: bug: seed generation & display should come after account creation
Currently, seed is generated upfront and shown to the user, before warp-ipfs is asked to create the account with the given seed. This seems a bit atypical to how this UX is usually done: recover seed is show **after** the account is already created.

Moreover, this has the side-effect of Uplink having to generate the code, while warp-ipfs has the code to do so, if `None` is passed. i-e unnecessary duplication of code.

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Reorders the pages in account creation. Previously it went Password -> Create/Import -> Phrases -> Username.
  Now: Password -> Create/Import -> Username -> Phrases.

### Which issue(s) this PR fixes 🔨

- Resolve #1968

### CODE REVIEW

**Review by phillsatellite — APPROVED** [review]

File: ui/src/layouts/log_in/copy_seed_words.rs [hunk 1]
```diff
@@ -24,20 +32,18 @@ pub fn Layout(cx: Scope, page: UseState<AuthPages>, seed_words: UseRef<String>)
...
-    let words = use_future(cx, (), |_| {
-        to_owned![seed_words];
-        async move {
-            let mnemonic = warp::crypto::keypair::generate_mnemonic_phrase(
-                warp::crypto::keypair::PhraseType::Standard,
-            )
-            .into_phrase();
-
-            seed_words.set(mnemonic.clone());
+    let words = use_future(cx, (), |_| async move {
```
Comment (dariusc93) [inline ui/src/layouts/log_in/copy_seed_words.rs:35]: Just as a note, warp does generate a mnemonic phrase if the `passphrase` field is `None`, in which case you can access it after the account creation in `IdentityProfile::passphrase`

Comment (stavares843) [reply ui/src/layouts/log_in/copy_seed_words.rs:35]: marking as resolved to merge 

cc @Flemmli97 if you wanna add that in another PR
