### PR TITLE
fix(lang): Lang fixes

### LINKED ISSUE #620: UI - Settings - Typos (missing sentence ending dots)
Since all the description sentences for Settings element descriptions ends with a dot, it would make sense to add these on the ones that are missing it:

Settings General:
image

Settings Developer:
image

### LINKED ISSUE #645: UI - Locales/Translations - Buttons and texts are not linked to locales files
While updating the spanish translations for the app, I found there are some buttons and texts in the app that are "hardcoded" to english instead of using translation files (or at least I did not find these in the English file):

- On Chats:
- "Create group" tooltip and "Create DM"
- Timestamp is hardcoded to english

image
image
image

- On Friends Blocked List:
- friends.requested adds the word "now" at the end, so on Spanish it would state "solicitada now" instead of "solicitada ahora", we could remove the "now" or add it to locales as well
image

- On Settings Extensions:
- Installed, Explore and Settings buttons
- On Settings Extensions - Explore, the "SEARCH EXTENSIONS" text and "Extension name or description." placeholder
image

- On Settings Developer:
- Test Notifications button
- "Test Notification" text and "Sends a test notification." description.
image

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Add missing dots to settings description
- Reorganized settings translation to match the current layout
- Add missing localization for buttons/texts
- Fix time stamps not being localized

### Which issue(s) this PR fixes 🔨

- Resolve #620
- Resolve #645

### CODE REVIEW

**Review by phillsatellite — APPROVED** [review]

File: common/src/language/mod.rs [hunk 1]
```diff
@@ -43,6 +43,14 @@ pub fn change_language(new_language: String) -> String {
     }
 }
 
+pub fn get_id_of(language: &String) -> String {
```
Comment (dariusc93) [inline common/src/language/mod.rs]:
```suggestion
pub fn get_id_of(language: &str) -> String {
```

**Review by dariusc93 — APPROVED** [review]
LGTM. Left one small suggestion (non blocking)
