### PR TITLE
fix(messages): dont use LinkFinder::spans

### LINKED ISSUE #745: Chat - sending " characters doesn't display properly
STR:
- go to chat
- send "hogan2" with the "
- appears like this

image

dev, macOS

### PR DESCRIPTION
**Pull request by sdwoodbury**
### What this PR does 📖

- link preview
image

- without breaking punctuation
image

### Which issue(s) this PR fixes 🔨

- Resolve #745

### CODE REVIEW

**Review by dariusc93 — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

File: kit/src/components/message/mod.rs [hunk 1]
```diff
@@ -268,11 +265,22 @@ fn ChatText(cx: Scope<ChatMessageProps>) -> Element {
         _ => rsx!(e.as_str()),
     });
 
+    // not really
```
Comment (stavares843) [inline kit/src/components/message/mod.rs:268]: is not very clear 😂

File: kit/src/components/message/mod.rs [hunk 2]
```diff
@@ -256,7 +252,8 @@ fn ChatText(cx: Scope<ChatMessageProps>) -> Element {
         .map(|e| e.as_str().to_string())
         .collect();
 
-    let texts = finder.spans(&cx.props.text).map(|e| match e.kind() {
+    // this is broken. may be fixed later.
```
Comment (stavares843) [inline kit/src/components/message/mod.rs:255]: does this need a ticket?

**Review by phillsatellite — APPROVED** [review]

File: kit/src/components/message/mod.rs (hunk 2 above)
Comment (sdwoodbury) [reply kit/src/components/message/mod.rs:255]: Idk. I assume it formats links somehow but am not sure. Would have to verify with @Flemmli97
