### PR TITLE
fix(overlays): temporary fix for windows overlay bug

### LINKED ISSUE #804: bug(settings): Uplink Overlay Causes Crash on App Unlock on Windows
Issue: If the Uplink overlay is enabled, the app will crash when unlocking. 

Steps to reproduce:
1. Open and Unlock Uplink
2. Go to settings
3. Select settings and enable overlay
Image
4. Close Uplink
5. Reopen Uplink and attempt to unlock (this is when it should crash)

Bonus Bug: After creating this crash, users may feel the instinct to run as an administrator. This creates a second bug where Uplink tries to create a new folder, uplink.exe.WebView2, in 'C:\Program Files\uplink\bin' 

Workaround is to go into the state.json and change "enable_overlay": true, -> "enable_overlay": false,

### PR DESCRIPTION
**Pull request by WanderingHogan**
### What this PR does 📖
This disables the overlay which was causing windows sign in to fail just on windows.

We will need to go in and fix this when we get video/calling in for the overlay widget but for now this quick fix should be ok

Here is a test build:
https://drive.google.com/file/d/1IB2B31LjPrGnStIBHk-5I5wDR9ZOCfyi/view?usp=sharing
- 

### Which issue(s) this PR fixes 🔨

- Resolve #804

### CODE REVIEW

File: ui/src/components/settings/sub_pages/general.rs [hunk 1]
```diff
@@ -36,9 +36,11 @@ pub fn GeneralSettings(cx: Scope) -> Element {
                 section_label: get_local_text("settings-general.overlay"),
                 section_description: get_local_text("settings-general.overlay-description"),
                 Switch {
-                    active: state.read().configuration.general.enable_overlay,
+                    // TODO: This overlay causes a crash in windows
+                    disabled: if cfg!(target_os = "windows") {true } else {false},
```
Comment (dariusc93) [inline ui/src/components/settings/sub_pages/general.rs]: It will only return false if the target isnt windows

```suggestion
                    disabled: cfg!(target_os = "windows"),
```

File: ui/src/components/settings/sub_pages/general.rs [hunk 2]
```diff
@@ -36,9 +36,11 @@ pub fn GeneralSettings(cx: Scope) -> Element {
...
+                    active: if cfg!(target_os = "windows") {false } else {state.read().configuration.general.enable_overlay},
```
Comment (dariusc93) [inline ui/src/components/settings/sub_pages/general.rs]:
```suggestion
                    active: cfg!(not(target_os = "windows")) && state.read().configuration.general.enable_overlay,
```

File: ui/src/components/settings/sub_pages/general.rs [hunk 3]
```diff
@@ -36,9 +36,11 @@ pub fn GeneralSettings(cx: Scope) -> Element {
...
                     onflipped: move |e| {
-                        state.write().mutate(Action::Config(ConfigAction::SetOverlayEnabled(e)));
+                        state.write().mutate(Action::Config(ConfigAction::SetOverlayEnabled(if cfg!(target_os = "windows") {false } else {e})));
```
Comment (dariusc93) [inline ui/src/components/settings/sub_pages/general.rs]:
```suggestion
                        state.write().mutate(Action::Config(ConfigAction::SetOverlayEnabled(cfg!(not(target_os = "windows")) && e )));
```

Comment (dariusc93) [inline ui/src/components/settings/sub_pages/general.rs]:
```suggestion
                        state.write().mutate(Action::Config(ConfigAction::SetOverlayEnabled(cfg!(not(target_os = "windows")) && e )));
```

**Review by dariusc93 — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]

File: ui/src/components/settings/sub_pages/general.rs (hunk 3 above)
Comment (WanderingHogan) [reply ui/src/components/settings/sub_pages/general.rs]: accepted the other one

**Comment by WanderingHogan** [comment]
thank you @dariusc93

**Review by stavares843 — APPROVED** [review]
