### PR TITLE
fix(chats): fix notifications and chats view

### LINKED ISSUE #306: Notifications - Notification sound not coming in
**Issue:** If the User has only 1 friend added, and they are exploring through the app (not in that active chat) they won't get any sound when they receive new messages, like the app thinks the user is still in that active chat, even though they are in Settings/Files/etc. If the User is focused outside of the app Notification sound works fine

**OS:**
-Windows
-Mac

**STR:**
1, Add one friend on Uplink 
2. Start a chat with them
3. Now leave the chat, but have the other user continue to message you 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/219460259-a04ffe4e-efef-4a18-97a8-506e6736a506.mov

### PR DESCRIPTION
**Pull request by sdwoodbury**
### What this PR does 📖

- don't clear the active chat when leaving the chats view 
- play a notification for the active chat if a message is received while not on the chats view 
- add a chat to the sidebar if a message is received. There wasn't a ticket for this but it seems weird to not know someone is messaging you unless you explicitly click the "chat with" button. 

### Which issue(s) this PR fixes 🔨

- Resolve #306 #459 

### Additional comments 🎤
I left in the addition to `utils` in case someone wants to use it later. I commented it out to avoid a clippy warning.

### CODE REVIEW

**Comment by phillsatellite** [comment]
@sdwoodbury this is a freaking awesome PR. When you hide a chat and get a new message from them it will re appear in the sidebar instantly but I think we needs to decide on how we want the hide chat to behave. This obviously is non blocking just wanted to mention it. Awesome job 🔥

File: common/src/state/mod.rs [hunk 1]
```diff
@@ -343,9 +343,9 @@ impl State {
                 // todo: don't load all the messages by default. if the user scrolled up, for example, this incoming message may not need to be fetched yet.
                 self.add_msg_to_chat(conversation_id, message);
 
-                if self.chats.in_sidebar.contains(&conversation_id) {
-                    self.send_chat_to_top_of_sidebar(conversation_id);
-                }
+                //if self.chats.in_sidebar.contains(&conversation_id) {
```
Comment (lgmarchi) [inline common/src/state/mod.rs:346]: Not better to already remove this commented code?

File: ui/src/utils/lifecycle.rs [hunk 2]
```diff
@@ -1,11 +1,11 @@
-use dioxus::prelude::*;
-
-pub fn use_on_unmount<F: FnOnce() + 'static>(cx: &ScopeState, on_unmount: F) -> &LifeCycle<F> {
-    cx.use_hook(|| LifeCycle {
-        on_unmount: Some(on_unmount),
-    })
-}
+//use dioxus::prelude::*;
 
+// pub fn use_on_unmount<F: FnOnce() + 'static>(cx: &ScopeState, on_unmount: F) -> &LifeCycle<F> {
```
Comment (lgmarchi) [inline ui/src/utils/lifecycle.rs:3]: Something here, not better to remove already commented code?

**Review by lgmarchi — APPROVED** [review]
Nice PR. Just left some comments non blocking.

File: common/src/state/mod.rs (hunk 1 above)
Comment (sdwoodbury) [reply common/src/state/mod.rs:346]: not necessarily this time. The thing Phill mentioned that we need to decide on is what got commented out here.

File: ui/src/utils/lifecycle.rs (hunk 2 above)
Comment (sdwoodbury) [reply ui/src/utils/lifecycle.rs:3]: image
