### PR TITLE
fix(DragEvent): Fix drag event on Linux

### LINKED ISSUE #1507: bug(chat): Drag/Drop not working on LInux
**Issue:**
Like title says, on Linux drag/drop is not working on chat or files 

**OS:**
Linux

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/4531a0d3-7f84-4256-98da-aa052333a271

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. : Fix drag event on Linux

https://github.com/Satellite-im/Uplink/assets/63157656/e31094a4-fe86-423d-8b42-a9f0b6147f5b

### Which issue(s) this PR fixes 🔨

- Resolve #1507

### CODE REVIEW

File: ui/src/utils/get_drag_event.rs [hunk 1]
```diff
@@ -8,3 +8,5 @@ pub fn get_drag_event() -> FileDropEvent {
 
 pub static DRAG_EVENT: Lazy<RwLock<FileDropEvent>> =
     Lazy::new(|| RwLock::new(FileDropEvent::Cancelled));
+
+pub static BLOCK_CANCEL_DRAG_EVENT_FOR_LINUX: Lazy<RwLock<bool>> = Lazy::new(|| RwLock::new(false));
```
Comment (sdwoodbury) [inline ui/src/utils/get_drag_event.rs:12]: if this only gets read from and written to in one place, this could also be an `AtomicBool`. Not that it matters much, just might be a little faster.

**Review by sdwoodbury — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Comment by stavares843** [comment]
i resolved the chat above to merge

File: ui/src/utils/get_drag_event.rs (hunk 1 above)
Comment (lgmarchi) [reply ui/src/utils/get_drag_event.rs:12]: I wrote down this. I will improve in a next opportunity.
