### PR TITLE
fix(chat): Fix wrong timestamp

### LINKED ISSUE #790: bug(ui): timestamps are appearing as seconds ago
**Issue:**
In the sidebar when you get a message in and the timestamp updates it will only ever say seconds ago. I sent a message and 5 minutes later the timestamp appeared as '4 seconds ago'

**OS:**
All

**Screenshot:**
Screenshot 2023-05-05 at 3 44 54 PM

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fixes timestamp for last message calculated wrongly

### Which issue(s) this PR fixes 🔨

- Resolve #790

### CODE REVIEW

File: kit/src/components/user/mod.rs [hunk 1]
```diff
@@ -34,7 +34,7 @@ pub fn get_time_ago(cx: &Scope<Props>) -> String {
     let duration: std::time::Duration = match c.to_std() {
         // for the sidebar, don't want the timestamp to increment a few seconds every time the typing indicator comes over.
         // prevent this by rounding down and giving a duration in minutes only.
-        Ok(d) => std::time::Duration::from_secs(d.as_secs() / 60),
+        Ok(d) => std::time::Duration::from_secs(d.as_secs() / 60 * 60),
```
Comment (WanderingHogan) [inline kit/src/components/user/mod.rs:37]: could you just remove the divide by 60 here?

**Review by phillsatellite — APPROVED** [review]

File: kit/src/components/user/mod.rs (hunk 1 above)
Comment (Flemmli97) [reply kit/src/components/user/mod.rs:37]: i thought the point was to not have it as seconds? this way it only displays at most as minutes.
since e.g. 40 sec -> 0 sec -> "now"
or 65 -> 60 -> 1 min

Comment (WanderingHogan) [reply kit/src/components/user/mod.rs:37]: I was just trying to point out

`std::time::Duration::from_secs(d.as_secs()),`

is always going to be the same as 

`std::time::Duration::from_secs(d.as_secs() / 60 * 60),`, 

right?

Comment (Flemmli97) [reply kit/src/components/user/mod.rs:37]: no actually. as its an int division. so if e.g. `d.as_secs()` is 40 then `40 / 60 * 60` would be 0

Comment (WanderingHogan) [reply kit/src/components/user/mod.rs:37]: oh, cool. I did not know that

Comment (WanderingHogan) [reply kit/src/components/user/mod.rs:37]: thank you :)

**Review by WanderingHogan — APPROVED** [review]
