### PR TITLE
fix(Markdown):  Fix markdown issues: Jump line, **bold**, code block

### LINKED ISSUE #673: bug(ui): Messages arent sending with correct format when entering new lines
**Issue:**
If you have a message like:
Look at this 

New Message 

It will appear in chat after sent like:
Look at this 
New Message 

It will be missing the new line that was entered when typing 

**OS:**
All

**Screen recording:**

https://user-images.githubusercontent.com/93608357/232878669-f7ea658a-7bc1-4288-ac9f-6a0bbf1e1c72.mov

### LINKED ISSUE #1006: bug(chat): Using a markdown will start a new line
**Issue:**
When a user uses a markdown in chat it will start a new line after the word with the markdown

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/352b72e8-6f94-4ad1-8639-45150e186fe7

### LINKED ISSUE #1012: bug(markdown): Spaces appear as "&nbsp;" w/ markdowns
**Issue:**
When you paste code into the chat and wrap it in `` any spaces used for that code will have "&nbsp;" 

**OS:**
All

**Screenshot:**
image

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. fix(Markdown):  Fix markdown issues: Jump line, **bold**, code block
image

### Which issue(s) this PR fixes 🔨

- Resolve #1006 
- Resolve #1012 
- Resolve #673

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hey bro just a quick question, is this intended? I pasted some code in there and use " ` ` ` " but appeared like an empty box

https://github.com/Satellite-im/Uplink/assets/93608357/ac7badc0-b538-4b02-bb84-b0932cd7612d

**Comment by lgmarchi** [comment]
> Hey bro just a quick question, is this intended? I pasted some code in there and use " ` ` ` " but appeared like an empty box
> 
>  Screen.Recording.2023-07-21.at.11.31.15.AM.mov

Not intended, but it is a problem from markdown, it happens on dev as well, we can open a ticket to work on this in the future

**Review by phillsatellite — APPROVED** [review]

File: kit/src/components/message/mod.rs [hunk 1]
```diff
@@ -366,9 +367,57 @@ fn ChatText(cx: Scope<ChatMessageProps>) -> Element {
...
+                            .push_str(&format!("<pre><code class=\"language-{}\">", language)),
+                        _ => html_output.push_str("<pre><code class=\"language-rust\">"),
+                    }
+                }
+                pulldown_cmark::Event::End(pulldown_cmark::Tag::CodeBlock(_)) => {
+                    let line_trim = line.trim();
+                    if in_code_block && line_trim == "```" {
+                        in_code_block = false;
+                        html_output.push_str("</code></pre>");
+                        html_output.push_str("</code></pre>");
```
Comment (stavares843) [inline kit/src/components/message/mod.rs:433]: is this duplicate in purpose? 🔨

**Review by stavares843 — APPROVED** [review]

File: kit/src/components/message/mod.rs (hunk 1 above)
Comment (lgmarchi) [reply kit/src/components/message/mod.rs:433]: Yes, but to be honest, it is missing a commentary why I wrote it duplicated, thanks to remember me

File: kit/src/components/message/mod.rs [hunk 2]
```diff
@@ -369,9 +370,57 @@ fn ChatText(cx: Scope<ChatMessageProps>) -> Element {
...
+    for line in text_lines {
+        let parser = pulldown_cmark::Parser::new_ext(line, options);
+        for event in parser {
+            match event {
+                pulldown_cmark::Event::Start(Tag::Paragraph) => {
+                    in_paragraph = true;
+                    html_output.push_str("<p>");
+                }
+                pulldown_cmark::Event::End(Tag::Paragraph) => {
+                    in_paragraph = false;
```
Comment (dariusc93) [inline kit/src/components/message/mod.rs:397]: Shouldnt the end paragraph tag be outputted here too?

File: kit/src/components/message/mod.rs [hunk 3]
```diff
@@ -369,9 +370,57 @@ fn ChatText(cx: Scope<ChatMessageProps>) -> Element {
...
+                        &mut html_output,
+                        std::iter::once(pulldown_cmark::Event::Text(txt)),
+                    );
+                }
+                pulldown_cmark::Event::Start(pulldown_cmark::Tag::CodeBlock(code_block_kind)) => {
+                    in_code_block = true;
+                    match code_block_kind {
+                        CodeBlockKind::Fenced(language) => html_output
+                            .push_str(&format!("<pre><code class=\"language-{}\">", language)),
+                        _ => html_output.push_str("<pre><code class=\"language-rust\">"),
```
Comment (dariusc93) [inline kit/src/components/message/mod.rs]: Might not be best to default to rust for this portion. Usually default would be something generic like text. What are all the options for `CodeBlockKind::Fenced`? probably could do something like 

```rust
let output = match code_block_kind {
    CodeBlockKind::Fenced(language) => language.to_string(), //This is assuming `Display` or `ToString` is implemented
    _ => "text".to_string(), //Assuming `language-text` or something along the like is available
};
html_output.push_str(&format!("<pre><code class=\"language-{}\">", language));
```

Note that the above snippet is just an example since im only guessing at what the output might be there right now

File: kit/src/components/message/mod.rs (hunk 2 above)
Comment (lgmarchi) [reply kit/src/components/message/mod.rs:397]: Actually, if I tag it, will jump one more line than necessary, so will bring message with error.

File: kit/src/components/message/mod.rs (hunk 3 above)
Comment (lgmarchi) [reply kit/src/components/message/mod.rs]: Hum... Ok, I did it like an easter egg, but no problem, I can change it to just a text code

Comment (lgmarchi) [reply kit/src/components/message/mod.rs]: I fixed it in other way, but it is working now

File: kit/src/components/message/mod.rs [hunk 4]
```diff
@@ -368,11 +369,76 @@ fn ChatText(cx: Scope<ChatMessageProps>) -> Element {
...
+
+    let mut text_lines: Vec<&str> = txt.split('\n').collect();
     let mut html_output = String::new();
-    pulldown_cmark::html::push_html(&mut html_output, parser);
-    html_output.replace("<p>", "").replace("</p>", "")
+    let mut in_paragraph = false;
+    let mut in_code_block = false;
+    let mut add_text_language = true;
+
+    for line in &mut text_lines {
```
Comment (dariusc93) [inline kit/src/components/message/mod.rs:383]: You shouldnt need to have a mutable reference here. You could just own `line` and use `mut line`. This would also remove the `mut text_lines` above when splitting.

File: kit/src/components/message/mod.rs [hunk 5]
```diff
@@ -368,11 +369,76 @@ fn ChatText(cx: Scope<ChatMessageProps>) -> Element {
...
+                            };
+
+                            html_output
+                                .push_str(&format!("<pre><code class=\"language-{}\">", language))
+                        }
+                        _ => html_output.push_str("<pre><code class=\"language-text\">"),
+                    }
+                }
+                pulldown_cmark::Event::End(pulldown_cmark::Tag::CodeBlock(_)) => {
+                    let line_trim = line.trim();
```
Comment (dariusc93) [inline kit/src/components/message/mod.rs]: any reason why we cant move this above to the beginning of the iterator?

File: kit/src/components/message/mod.rs (hunk 4 above)
Comment (lgmarchi) [reply kit/src/components/message/mod.rs:383]: I think it can affect behavior of the code, when I try to do it, it says new value to line is never used

File: kit/src/components/message/mod.rs (hunk 5 above)
Comment (lgmarchi) [reply kit/src/components/message/mod.rs]: No reason Darius, I will move it.

**Review by dariusc93 — APPROVED** [review]
