### PR TITLE
fix(reload): disable reload hotkey to stop refresh breaking bug

### LINKED ISSUE #1757: bug(keyBindings): Disable reload with control+shift+R
**Issue:**
On Windows when you press Control+Shift+R it reloads Uplink and then causes the app to be invisible 

**OS:**
Windows

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/dd561fa2-d519-48be-ab05-3273f1484543

### PR DESCRIPTION
**Pull request by Jekrimo**
### What this PR does 📖

- Add new js file to handle stopping the reload for hotkey's

### Which issue(s) this PR fixes 🔨

- Resolve #1757

### CODE REVIEW

File: ui/src/layouts/chats/presentation/chat/mod.rs [hunk 1]
```diff
@@ -55,6 +55,8 @@ pub fn Compose(cx: Scope) -> Element {
     let identity_profile = use_state(cx, DID::default);
 
     let eval_provider = use_eval(cx);
+    let script = DISABLE_RELOAD;
+    let _ = eval_provider(&script);
```
Comment (dariusc93) [inline ui/src/layouts/chats/presentation/chat/mod.rs]:
```suggestion
    let _ = eval_provider(script);
```

**Review by phillsatellite — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]
