### PR TITLE
update(Chat): Fix drag and drop on chats on Windows OS

### LINKED ISSUE #1195: bug(files): Issues when drag and dropping files in chat *Windows*
**Issue:**
There seems to be some problems with drag and drop files within chat on Windows. 

-First to notice is the box that should appear when a user is dragging a file into chat only appears on the first time user attempts to drag and drop file after opening the app. Any time after that it does not appear 

-Second to notice is, if you have multiple chats in the sidebar and you drag and drop a file, the file will only ever appear in the top chat

-Third if the drag and drop does not work at all, the user can navigate to the Files page and then back to Chat and the drag and drop will "work" again 

Continuing to test this but I wanted to note down some of the stuff that Sheldon, Hogan, Sara and I have found this morning  

**OS:**
Windows

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/8865c884-3506-46a1-823d-f0db22cd7e0d

### PR DESCRIPTION
**Pull request by lgmarchi**
### Tested on MacOS 

https://github.com/Satellite-im/Uplink/assets/63157656/978fdab2-587c-4b9d-91c3-1c38f0cf708b

### Tested on Windows 

https://github.com/Satellite-im/Uplink/assets/63157656/303ff83a-876c-4de4-832a-5917a5b77fa0

### Which issue(s) this PR fixes 🔨

- Resolve #1195

### CODE REVIEW

**Review by stavares843 — APPROVED** [review]

File: ui/src/layouts/chat.rs [hunk 1]
```diff
@@ -37,3 +108,91 @@ pub fn ChatLayout(cx: Scope) -> Element {
...
+    window: &DesktopContext,
+    drag_event: &UseRef<Option<FileDropEvent>>,
+) -> Vec<PathBuf> {
+    *drag_event.write_silent() = Some(get_drag_event::get_drag_event());
+    let mut new_files_to_upload = Vec::new();
+    loop {
+        let file_drop_event = get_drag_event::get_drag_event();
+        match file_drop_event {
+            FileDropEvent::Hovered { paths, .. } => {
+                if verify_if_are_valid_paths(&paths) {
```
Comment (sdwoodbury) [inline ui/src/layouts/chat.rs:151]: don't need to fix this now, but the proper grammar is "if paths are valid".  A more concise name is "verify_paths"

File: ui/src/layouts/chat.rs [hunk 2]
```diff
@@ -37,3 +108,91 @@ pub fn ChatLayout(cx: Scope) -> Element {
...
+                    } else {
+                        script.push_str(&FEEDBACK_TEXT_SCRIPT.replace(
+                            "$TEXT",
+                            &format!(
+                                "{} {}!",
+                                paths.len(),
+                                get_local_text("files.one-file-to-upload")
+                            ),
+                        ));
+                    }
```
Comment (sdwoodbury) [inline ui/src/layouts/chat.rs:171]: also don't need to fix this now but it could be condensed to
```
let local_text = if paths.len() > 1 { ... } else { ... };
script.push_str(...);
```

**Review by sdwoodbury — APPROVED** [review]

**Comment by stavares843** [comment]
@lgmarchi merging, but stu added a few comments above - i only clicked on resolved to be able to merge 🔨

**Comment by lgmarchi** [comment]
> @lgmarchi merging, but stu added a few comments above - i only clicked on resolved to be able to merge 🔨

Both fixed on my current PR. Thanks @stavares843 and @sdwoodbury!
