### PR TITLE
fix(Attachments): Limit files per message and remove persistance when switching chat

### LINKED ISSUE #1026: bug(chat): If too many files are attached to a message, it will never send
**Issue:**
Like the title says, within chat if you send a message with attachments but you attach too many files to it they will never send or appear in chat 

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/9400178b-0902-453e-9029-e1ff429161ee

### LINKED ISSUE #1040: bug(chat): when sending a file filename is barely visible
SRT:
- go to chat
- send file
- name isnt visible

Captura de ecrã 2023-07-24, às 23 10 51

Captura de ecrã 2023-07-24, às 23 11 43

macOS, m1

### LINKED ISSUE #1046: bug(chat): Files will persist when switching chats
**Issue:**
If you attach a file to send in chat, then switch chats the file will persist 

**OS:**
all

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/242fd1d6-a1e2-4544-868e-72707fbffada

### PR DESCRIPTION
**Pull request by lgmarchi**
### 4. Improve UI when attach files 
a. Let files attached in vertical now, with document icon with extension or thumbnail if file is image 
image

b. When files in chat, they are aligned now, with document and extension when they do not have thumbnail
image

c. Files aligned when they are loading to be sent as well

image

### Which issue(s) this PR fixes 🔨

- Resolve #1026 
- Resolve #1046 
- Resolve #1040

### CODE REVIEW

**Comment by dariusc93** [comment]
I wonder if we could just handle the from error instead since this will likely change in the near future where there can be more than 8 files

**Comment by lgmarchi** [comment]
> I wonder if we could just handle the from error instead since this will likely change in the near future where there can be more than 8 files

I was thinking about it as well, is not better to already five a feedback for user before he tries to send message? 

He will already know, maximum possible is 8, and we are going let user just attach 8 files per time as well.

**Review by stavares843 — COMMENTED** [review]
the toast isn't very visible because user is looking at the bottom of the chat and the toast is in the top right corner maybe we could use this type of error instead

Captura de ecrã 2023-07-25, às 23 01 39

instead of that would say ''Maximum of 8 files can be sent in a single message.''

**Comment by phillsatellite** [comment]
Wanted to also note

on MacOS and Linux I would get this panic each time I sent over 8 files in chat 

Screenshot 2023-07-26 at 6 14 12 AM

And when I tried to compile on Windows I would get this error and app wouldn't open 

image

**Comment by lgmarchi** [comment]
> Wanted to also note
> 
> on MacOS and Linux I would get this panic each time I sent over 8 files in chat
> 
> Screenshot 2023-07-26 at 6 14 12 AM
> And when I tried to compile on Windows I would get this error and app wouldn't open
> 
> image

Which method did you use to attach files? Drag and Drop, File Explorer ou Paste from clipboard? 

And this panic happened when did you click in send files button?

**Review by stavares843 — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

File: kit/src/components/embeds/file_embed/mod.rs [hunk 1]
```diff
@@ -244,3 +300,39 @@ pub fn FileEmbed<'a>(cx: Scope<'a, Props<'a>>) -> Element<'a> {
         }
     ))
 }
+
+fn get_file_thumbnail_if_is_image(filepath: PathBuf, filename: String) -> String {
```
Comment (dariusc93) [inline kit/src/components/embeds/file_embed/mod.rs:304]: This shouldnt be needed since the type and thumbnail is determined from within constellation unless there is some other use for it (see https://github.com/Satellite-im/Uplink/pull/828)

Comment (lgmarchi) [reply kit/src/components/embeds/file_embed/mod.rs:304]: It is necessary, because is using before send messages, using thumbnail on files attachments

**Comment by stavares843** [comment]
missing linter 🔨 
https://github.com/Satellite-im/Uplink/actions/runs/5684449306/job/15407188943?pr=1045

File: kit/src/components/embeds/file_embed/mod.rs (hunk 1 above)
Comment (dariusc93) [reply kit/src/components/embeds/file_embed/mod.rs:304]: I will allow it for now but might want to rethink this for the future as this is moreso redundant as it might misrepresent the thumbnail that is actually generated. A couple of things to note of would be in the PR mentioned above. A workaround might be to upload the images directly to constellation and change the `Location` to `Location::Constellation` and point to the file itself when calling `RayGun::attach`.

File: common/src/state/mod.rs [hunk 2]
```diff
@@ -851,6 +855,12 @@ impl State {
         }
     }
 
+    fn clear_chat_attachments(&mut self, chat_id: &Uuid) {
+        if let Some(c) = self.chats.all.get_mut(chat_id) {
+            c.files_attached_to_send = Vec::new();
```
Comment (dariusc93) [inline common/src/state/mod.rs]:
```suggestion
            c.files_attached_to_send.clear();
```

**Review by dariusc93 — APPROVED** [review]
Just one small suggestion and it can merge
