### PR TITLE
fix(friends): Fix did hash for outgoing/incoming being reversed

### LINKED ISSUE #1235: bug(friends): hash is displayed backwards
image

FR someone and the last X digits of their id (everything after the #) are shown backwards on the friends page.

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fixes hash being displayed in reverse for outgoing/incoming friend requests.
  - Reason `Identity#short_id` is not used like in friend page is the short id is not present if the identity is not resolved fully

### Which issue(s) this PR fixes 🔨

- Resolve #1235

### CODE REVIEW

File: ui/src/components/friends/incoming_requests/mod.rs [hunk 1]
```diff
@@ -97,7 +97,8 @@ pub fn PendingFriends(cx: Scope) -> Element {
                 let _status_message = friend.status_message().unwrap_or_default();
                 let did = friend.did_key();
                 let did2 = did.clone();
-                let did_suffix: String = did.to_string().chars().rev().take(6).collect();
+                let mut did_suffix: String = did.to_string();
+                did_suffix = did_suffix.char_indices().nth_back(6).map(|(i,_)|did_suffix[i..].to_string()).unwrap_or_default();
```
Comment (dariusc93) [inline ui/src/components/friends/incoming_requests/mod.rs]: Instead, you can use `Identity::short_id` in which you could do something like

```rust
let did_suffix = friend.short_id().to_string();
```

File: ui/src/components/friends/outgoing_requests/mod.rs [hunk 2]
```diff
@@ -61,7 +61,8 @@ pub fn OutgoingRequests(cx: Scope) -> Element {
             friends_list.into_iter().map(|friend| {
                 let did = friend.did_key();
                 let did2 = did.clone();
-                let did_suffix: String = did.to_string().chars().rev().take(6).collect();
+                let mut did_suffix: String = did.to_string();
+                did_suffix = did_suffix.char_indices().nth_back(6).map(|(i,_)|did_suffix[i..].to_string()).unwrap_or_default();
```
Comment (dariusc93) [inline ui/src/components/friends/outgoing_requests/mod.rs]: ditto

File: ui/src/components/friends/incoming_requests/mod.rs (hunk 1 above)
Comment (Flemmli97) [reply ui/src/components/friends/incoming_requests/mod.rs]: already in the description but it seems the short_id is not always present during requests?

**Comment by phillsatellite** [comment]
Noticed one thing while testing, the did will still appear reversed in the blocked tab, this happens on all os's. Other than that seemed good! 

Screenshot 2023-09-28 at 3 50 46 PM

**Review by lgmarchi — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

File: ui/src/components/friends/incoming_requests/mod.rs (hunk 1 above)
Comment (dariusc93) [reply ui/src/components/friends/incoming_requests/mod.rs]: If thats the case, maybe we can also set it in `get_uninitialized_identity`?

Comment (sdwoodbury) [reply ui/src/components/friends/incoming_requests/mod.rs]: i concur. it can be done like this: 

```
let pk = did.public_key_bytes();
let short: [u8; 8] = pk[pk.len() - 8..].try_into().map_err(|_e| warp::error::Error::OtherWithContext("did to short".into()))?;
default.set_short_id(short);
```

**Review by dariusc93 — APPROVED** [review]
