### PR TITLE
fix(UploadFileBar): Fixed upload file bar when user hover an image in side file storage

### LINKED ISSUE #1734: bug(files): block appears when dragging file on Files Page
**Issue:**
When you drag a photo to the top of the files page, a grey block will appear and will persist until you close the app and re open 

**OS:**
All

**STR:**
-Drag File to top of File Storage Page 

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/bc2cea4e-e9dd-499a-83b2-3adca8de54e9

### PR DESCRIPTION
**Pull request by lgmarchi**
### Which issue(s) this PR fixes 🔨

- Resolve #1734

### CODE REVIEW

**Comment by phillsatellite** [comment]
DM'd Lucas, on Linux it looks like the box still appears when you are dragging a file, I let him know that this is not something I think we would need to block the entire pr for but wanted to see if he had a quick fix for it still 👍 

https://github.com/Satellite-im/Uplink/assets/93608357/53e0a4e2-1271-4210-a424-7887619c8988

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

File: ui/src/utils/get_drag_event.rs [hunk 1]
```diff
@@ -1,8 +1,42 @@
...
+                .filter(|&path| {
+                    let data = path.to_string_lossy().to_string();
+                    !(data.contains("image/jpeg;base64") || data.contains("image/png;base64"))
+                })
+                .cloned()
+                .collect();
+            if filtered_paths.is_empty() {
+                return FileDropEvent::Cancelled;
+            }
+        }
```
Comment (dariusc93) [inline ui/src/utils/get_drag_event.rs]: Unless you will be doing something specific, you could merge the two conditions by doing something like

```rust
match DRAG_EVENT.read().clone() {
    FileDropEvent::Hovered { paths, .. } | FileDropEvent::Dropped { paths, .. } => {
         ....... 
    },
    .....
}
```

File: ui/src/utils/get_drag_event.rs [hunk 2]
```diff
@@ -1,8 +1,42 @@
...
+        FileDropEvent::Dropped { paths, .. } => {
+            let filtered_paths: Vec<PathBuf> = paths
+                .clone()
+                .iter()
+                .filter(|&path| {
+                    let data = path.to_string_lossy().to_string();
+                    !(data.contains("image/jpeg;base64") || data.contains("image/png;base64"))
```
Comment (dariusc93) [inline ui/src/utils/get_drag_event.rs:16]: If this is related to `PathBuf`, I dont think it would contain the base64 image header unless im missing something?

**Comment by phillsatellite** [comment]
Added label for Darius's comments above

File: ui/src/utils/get_drag_event.rs (hunk 2 above)
Comment (lgmarchi) [reply ui/src/utils/get_drag_event.rs:16]: It has when we drag images inside Uplink, on Linux system. This solution is just for Linux.

File: ui/src/utils/get_drag_event.rs (hunk 1 above)
Comment (lgmarchi) [reply ui/src/utils/get_drag_event.rs]: Done!

File: ui/src/utils/get_drag_event.rs (hunk 2 above)
Comment (lgmarchi) [reply ui/src/utils/get_drag_event.rs:16]: When I say Images, it is just thumbnails drag. Like we get a thumbnail and start to drag it from storage for example.

**Review by dariusc93 — APPROVED** [review]
