### PR TITLE
fix(Markdown): Fix code block on pinned messages

### LINKED ISSUE #1475: chore(markdown): fix markdown in pinned messages
STR:
- go to chat
- send a message with code
- pin
- it doesn't display the same in the pinned messages

image

macOS, m1

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1.  Fix code block on pinned messages
image

### Which issue(s) this PR fixes 🔨

- Resolve #1475

### CODE REVIEW

**Review by dariusc93 — APPROVED** [review]

**Review by stavares843 — COMMENTED** [review]
https://github.com/Satellite-im/Uplink/assets/29093946/e7f0f010-0336-4c50-a1f5-c56cc97020f6


sometimes appears with the proper layout sometimes doesn't 

macOS, m1

**Comment by phillsatellite** [comment]
Sara's comment above also happened on a m2 mac and Windows as well

**Review by stavares843 — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

File: ui/src/layouts/chats/presentation/chat/pinned_messages/mod.rs [hunk 1]
```diff
@@ -156,7 +168,8 @@ pub fn PinnedMessages(cx: Scope<'_, Props>) -> Element<'_> {
                         onclick: move |_| {
                             ch.send(ChannelCommand::GoToPinnedMessage{conversation_id, message_id, message_date, show_pinned: cx.props.show_pinned.clone()});
                         }
-                    })
+                    },
```
Comment (stavares843) [inline ui/src/layouts/chats/presentation/chat/pinned_messages/mod.rs]:
```suggestion
                    },
```
