### PR TITLE
fix(chat): Send button indicator

### LINKED ISSUE #695: UI - Send button does not change colors when just an emoji is selected
**Issue:**
In chat the send button should change from grey to blue (or whatever theme you have set). If you put just a emoji in the input box the send button doesn't recognize it as a char and will not change from grey

**OS:**
All

**STR:**
To show correct behavior type in the input box in chat (see send buttons color change)
To show bug put just an emoji 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/233470414-88371b40-654b-4989-9d64-050e4f8c9dc6.mov

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fix send button not changing color if using emojis

### Which issue(s) this PR fixes 🔨

- Resolve #695

### CODE REVIEW

File: ui/src/components/chat/compose/chatbar.rs [hunk 1]
```diff
@@ -275,8 +282,9 @@ pub fn get_chatbar<'a>(cx: &'a Scoped<'a, super::ComposeProps>) -> Element<'a> {
         is_disabled: disabled,
         onchange: move |v: String| {
             if let Some(id) = &active_chat_id {
-                can_send.set(!v.is_empty() || !files_to_upload.get().is_empty());
+                //can_send.set(!v.is_empty() || !files_to_upload.get().is_empty());
```
Comment (stavares843) [inline ui/src/components/chat/compose/chatbar.rs]: do we need the commented out code?

**Comment by stavares843** [comment]
Captura de ecrã 2023-04-26, às 16 43 09


ticket

vs

app in this branch

image


there's no emoji button

**Review by phillsatellite — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]
