### PR TITLE
fix(chat): Add missing unread indicator to chat button

### LINKED ISSUE #1187: bug(ui): Indicator missing on nav bar
**Issue:**
When you are not on the chat page and you receive a message you should get a red indicator that appears on the Chat tab with the number of unread messages here 

Screenshot 2023-09-01 at 6 09 19 PM

When you go back to the chat page, the indicator should clear out **but not clear out the unread messages on the actual chat** 

Screenshot 2023-09-01 at 6 12 25 PM

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Adds an unread indicator to the chat navigation button

### Which issue(s) this PR fixes 🔨

- Resolve #1187

### CODE REVIEW

File: ui/src/main.rs [hunk 1]
```diff
@@ -974,11 +974,24 @@ fn AppNav<'a>(
     let state = use_shared_state::<State>(cx)?;
     let navigator = use_navigator(cx);
     let pending_friends = state.read().friends().incoming_requests.len();
+    let unreads: u32 = state
```
Comment (sdwoodbury) [inline ui/src/main.rs]: this is cool. But I think we might want to only sum the unread messages from conversations which are in the sidebar. Otherwise, if someone hid a conversation which had unread messages, they could read all messages in the sidebar and yet there icon on the navbar would still be there.

**Comment by phillsatellite** [comment]
Hi @Flemmli97 I noticed some weird behavior on MacOS and Linux but could not replicate on Windows 

While testing I noticed that the notification count is showing 2x the amount of unread messages. So if a user has 5 unread messages the indicator will show as 10 unread messages

Linux
Screenshot 2023-09-07 at 4 30 34 PM

https://github.com/Satellite-im/Uplink/assets/93608357/4a3d6087-ac9a-46fc-a919-941ff76022fd

**Comment by Flemmli97** [comment]
> 

it might relate to the hidden chat problem. maybe you have a chat thats not in the sidebar that has coincidentally 5 msg. can you try with the new fix?

**Comment by phillsatellite** [comment]
So everything with the indicator now works great! Was about to approve but then I noticed this in the Settings tab. The highlight seems to stop at the end of the name in the Settings Nav, is this intended? 

**This Branch**

ThisBranch

**Dev Branch**

Screenshot 2023-09-08 at 3 39 04 PM

**Review by sdwoodbury — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]
