### PR TITLE
fix(chat): Fix sizes with some emoji in chat

### LINKED ISSUE #1764: bug(emoji): Various emojis are appearing small
**Issue:**
There are various emojis that are appearing small when you send them 

**Expected Behavior:**
These emojis should be the same size that the rest of the emojis appear as 

**Steps to reproduce:**
1. Open emoji selector 
2. Select one of these emojis & send
Screenshot 2024-01-24 at 3 37 18 PM
Screenshot 2024-01-24 at 3 47 00 PM
Screenshot 2024-01-24 at 3 47 53 PM
Screenshot 2024-01-24 at 3 50 08 PM
Screenshot 2024-01-24 at 3 50 45 PM
Screenshot 2024-01-24 at 3 51 29 PM
Screenshot 2024-01-24 at 3 52 49 PM
Screenshot 2024-01-24 at 3 55 11 PM
Screenshot 2024-01-24 at 3 59 10 PM
Screenshot 2024-01-24 at 3 57 54 PM

**OS:**
MacOS 
Linux (Ubuntu)
WindowsOS

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fixes issue with some messages with only emojis where the sizes are not matching

### Which issue(s) this PR fixes 🔨

- Resolve #1764

### CODE REVIEW

**Review by dariusc93 — APPROVED** [review]

**Comment by phillsatellite** [comment]
@Flemmli97 while testing I found some that are still showing up really small 

Screenshot 2024-02-16 at 11 06 13 AM
Screenshot 2024-02-16 at 11 15 53 AM
Screenshot 2024-02-16 at 11 24 35 AM
Screenshot 2024-02-16 at 11 38 49 AM

File: kit/src/components/message/mod.rs [hunk 1]
```diff
@@ -551,6 +551,7 @@ fn markdown(text: &str, emojis: bool) -> String {
     let txt = text.trim();
     if emojis {
         let r = replace_emojis(txt);
+        log::debug!("r {}, {:?}", r, r.chars());
```
Comment (stavares843) [inline kit/src/components/message/mod.rs]: can we remove this? 🔨

**Review by phillsatellite — APPROVED** [review]
