### PR TITLE
fix(chat): Move scroll button handling in its own thing

### LINKED ISSUE #1519: bug(chat): Scroll to bottom does not appear if only images are sent in chat
**Issue:**
Like title says if you start a chat and send enough images to scroll up (without sending any messages with text, then scroll to bottom will not appear 

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/7c4fa834-a6a4-4fb5-9dcb-f3208b32e71a

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Moves scroll button handling in its own handling logic. Not reliant on IntersectionObserver
- This should fix various issues with large messages causing scroll to not appear etc.

### Which issue(s) this PR fixes 🔨

- Resolve #1519

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hey Kevin! So first off wanted to say this is non-blocking I'm still cool with merging this in but I did wanna comment that I found some weird behavior. In mobile view scroll to bottom was appearing fine but for some reason on this one particular chat that I have the scroll to bottom wasnt appearing in mobile view although it appeared fine in desktop view. Again this is non-blocking I just wanted to mention in for us to keep an eye out in the future 💥  Otherwise great PR 😄 

https://github.com/Satellite-im/Uplink/assets/93608357/c79540b9-dea1-4a59-aaf8-5bb503b5face

File: ui/src/layouts/chats/presentation/messages/mod.rs [hunk 1]
```diff
@@ -69,6 +69,8 @@ pub enum MessagesCommand {
 }
 
 pub type DownloadTracker = HashMap<Uuid, HashSet<warp::constellation::file::File>>;
+const READ_SCROLL: &str = "return document.getElementById(\"messages\").scrollTop";
```
Comment (sdwoodbury) [inline ui/src/layouts/chats/presentation/messages/mod.rs]: I guess this is fine. Though if it was moved into the `chats/scripts/mod.rs` I think that would help us keep track of what scripts are being used.

**Review by sdwoodbury — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]
