### PR TITLE
fix(FileName): fix name for images from storage

### LINKED ISSUE #1520: bug(chat): File name missing when uploading from Uplink File Storage
**Issue:**
When you upload a file by clicking "Browse files" and select an image to send the file name will be missing. This only happens when you select an image to upload files like pdf's etc will show file name correctly 

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/f71328d3-f562-4465-8a20-8575b12ffba6

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Fix name for images from storage

https://github.com/Satellite-im/Uplink/assets/63157656/2bb64b5a-5b91-44df-845c-1ab0d6aa07af

### Which issue(s) this PR fixes 🔨

- Resolve #1520

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hey @lgmarchi noticed a minor issue, in chat its now showing the names next to all the images that were sent. This was replicated on all OS's 

Screenshot 2023-11-17 at 10 48 49 AM

**Comment by lgmarchi** [comment]
> Hey @lgmarchi noticed a minor issue, in chat its now showing the names next to all the images that were sent. This was replicated on all OS's
> 
> Screenshot 2023-11-17 at 10 48 49 AM

Fixed my friend!

File: kit/src/components/embeds/file_embed/mod.rs [hunk 1]
```diff
@@ -365,3 +323,25 @@ fn get_file_thumbnail_if_is_image(filepath: PathBuf, filename: String) -> String
     };
     image
 }
+
+fn show_download_button_if_enabled<'a>(
+    cx: Scope<'a, Props<'a>>,
+    with_download_button: bool,
+    btn_icon: common::icons::outline::Shape,
+) -> Element<'a> {
+    if with_download_button {
```
Comment (dariusc93) [inline kit/src/components/embeds/file_embed/mod.rs:332]: you might be able to do the following to simplify it

```rust
with_download_button.then_some(cx.render(rsx!(
            div {
                id: "file-embed-action-button",
                Button {
                    icon: btn_icon,
                    appearance: Appearance::Primary,
                    aria_label: "attachment-button".into(),
                    onpress: move |_| cx.props.on_press.call(()),
                }
            }
)))
```

so if its true, it will return `Element` (which is an alias of `Option`), otherwise it would return `None`.

**Review by dariusc93 — APPROVED** [review]
