### PR TITLE
fix(chat): Chatbar selection fix

### LINKED ISSUE #1763: bug(emojiSelector): Fix various issues with the text based emoji selector
**Issue:**
- [ ] Scrolling down with the mouse then using either Up or Down arrow keys will cause list to jump to the top 

**Expected behavior:**
If you scroll with your mouse then use the arrow keys, it should continue from wherever the user is at on the list and not jump to either the top or bottom of the list

https://github.com/Satellite-im/Uplink/assets/93608357/e20cd016-2eb2-4391-a107-9d43c8b62245

**Issue:**
- [ ] Pressing tab should auto select emoji 

**Expected behavior:**
When user presses tab it should select the emoji at the top of the list 

https://github.com/Satellite-im/Uplink/assets/93608357/e87c4027-ef37-44e4-ac5e-1f7530009287

**Issue:**
- [ ] If you use the arrow keys to go up or down, the scroll highlight will scroll to options the user cannot see 

**Expected behavior:**
Highlight should be visible entire time user is using up or down arrow keys to scroll 

https://github.com/Satellite-im/Uplink/assets/93608357/47262407-3c72-4c4d-a207-b75c1824dd53

**OS:**
These were replicated across all OS's

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fixes various issues in regards to chatbar suggestion outlined in the linked issue

### Which issue(s) this PR fixes 🔨

- Resolve #1763

### CODE REVIEW

**Review by phillsatellite — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]

File: kit/src/elements/textarea/rich_editor_handler.js [hunk 1]
```diff
@@ -29,12 +29,25 @@ function forwardevent(e) {
     return newEvent.defaultPrevented
 }
 
+function forwardeventDown(e) {
```
Comment (stavares843) [inline kit/src/elements/textarea/rich_editor_handler.js]:
```suggestion
function forwardEventDown(e) {
```
